"""create invoice_extractions and invoice_line_items

Revision ID: 0002_invoice_extraction_tables
Revises: 0001_create_documents_table
Create Date: 2026-09-01 17:50:29.516375+00:00

Stage 3 step 3. Adds the two extraction persistence tables and the
``extraction_status`` enum. Touches nothing in ``documents`` or the Stage 2
upload path.
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0002_invoice_extraction_tables'
down_revision: Union[str, None] = '0001_create_documents_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_extractions',
    sa.Column('extraction_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PROCESSING', 'COMPLETED', 'FAILED', name='extraction_status'), nullable=False),
    sa.Column('provider_name', sa.String(length=128), nullable=False),
    sa.Column('provider_model', sa.String(length=256), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('invoice_number_value', sa.Text(), nullable=True),
    sa.Column('invoice_number_confidence', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('invoice_date_value', sa.Text(), nullable=True),
    sa.Column('invoice_date_confidence', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('due_date_value', sa.Text(), nullable=True),
    sa.Column('due_date_confidence', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('vendor_name_value', sa.Text(), nullable=True),
    sa.Column('vendor_name_confidence', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('vendor_tax_id_value', sa.Text(), nullable=True),
    sa.Column('vendor_tax_id_confidence', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('customer_name_value', sa.Text(), nullable=True),
    sa.Column('customer_name_confidence', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('currency_value', sa.String(length=3), nullable=True),
    sa.Column('currency_confidence', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('subtotal_value', sa.Numeric(), nullable=True),
    sa.Column('subtotal_confidence', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('tax_amount_value', sa.Numeric(), nullable=True),
    sa.Column('tax_amount_confidence', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('total_amount_value', sa.Numeric(), nullable=True),
    sa.Column('total_amount_confidence', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.CheckConstraint("(status = 'PROCESSING' AND completed_at IS NULL AND failure_code IS NULL AND failure_message IS NULL) OR (status = 'COMPLETED' AND completed_at IS NOT NULL AND failure_code IS NULL AND failure_message IS NULL) OR (status = 'FAILED' AND completed_at IS NOT NULL AND failure_code IS NOT NULL)", name=op.f('ck_invoice_extractions_status_fields_consistent')),
    sa.CheckConstraint('attempt_number >= 1', name=op.f('ck_invoice_extractions_attempt_number_positive')),
    sa.CheckConstraint('currency_confidence IS NULL OR (currency_confidence >= 0 AND currency_confidence <= 1)', name=op.f('ck_invoice_extractions_currency_confidence_range')),
    sa.CheckConstraint('customer_name_confidence IS NULL OR (customer_name_confidence >= 0 AND customer_name_confidence <= 1)', name=op.f('ck_invoice_extractions_customer_name_confidence_range')),
    sa.CheckConstraint('due_date_confidence IS NULL OR (due_date_confidence >= 0 AND due_date_confidence <= 1)', name=op.f('ck_invoice_extractions_due_date_confidence_range')),
    sa.CheckConstraint('invoice_date_confidence IS NULL OR (invoice_date_confidence >= 0 AND invoice_date_confidence <= 1)', name=op.f('ck_invoice_extractions_invoice_date_confidence_range')),
    sa.CheckConstraint('invoice_number_confidence IS NULL OR (invoice_number_confidence >= 0 AND invoice_number_confidence <= 1)', name=op.f('ck_invoice_extractions_invoice_number_confidence_range')),
    sa.CheckConstraint('subtotal_confidence IS NULL OR (subtotal_confidence >= 0 AND subtotal_confidence <= 1)', name=op.f('ck_invoice_extractions_subtotal_confidence_range')),
    sa.CheckConstraint('tax_amount_confidence IS NULL OR (tax_amount_confidence >= 0 AND tax_amount_confidence <= 1)', name=op.f('ck_invoice_extractions_tax_amount_confidence_range')),
    sa.CheckConstraint('total_amount_confidence IS NULL OR (total_amount_confidence >= 0 AND total_amount_confidence <= 1)', name=op.f('ck_invoice_extractions_total_amount_confidence_range')),
    sa.CheckConstraint('vendor_name_confidence IS NULL OR (vendor_name_confidence >= 0 AND vendor_name_confidence <= 1)', name=op.f('ck_invoice_extractions_vendor_name_confidence_range')),
    sa.CheckConstraint('vendor_tax_id_confidence IS NULL OR (vendor_tax_id_confidence >= 0 AND vendor_tax_id_confidence <= 1)', name=op.f('ck_invoice_extractions_vendor_tax_id_confidence_range')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], name=op.f('fk_invoice_extractions_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('extraction_id', name=op.f('pk_invoice_extractions')),
    sa.UniqueConstraint('document_id', 'attempt_number', name='uq_invoice_extractions_document_id_attempt_number')
    )
    op.create_index('uq_invoice_extractions_one_active_per_document', 'invoice_extractions', ['document_id'], unique=True, postgresql_where=sa.text("status = 'PROCESSING'"))
    op.create_table('invoice_line_items',
    sa.Column('line_item_id', sa.Uuid(), nullable=False),
    sa.Column('extraction_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('description_value', sa.Text(), nullable=True),
    sa.Column('description_confidence', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('quantity_value', sa.Numeric(), nullable=True),
    sa.Column('quantity_confidence', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('unit_price_value', sa.Numeric(), nullable=True),
    sa.Column('unit_price_confidence', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('line_total_value', sa.Numeric(), nullable=True),
    sa.Column('line_total_confidence', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('description_confidence IS NULL OR (description_confidence >= 0 AND description_confidence <= 1)', name=op.f('ck_invoice_line_items_description_confidence_range')),
    sa.CheckConstraint('line_total_confidence IS NULL OR (line_total_confidence >= 0 AND line_total_confidence <= 1)', name=op.f('ck_invoice_line_items_line_total_confidence_range')),
    sa.CheckConstraint('position >= 0', name=op.f('ck_invoice_line_items_position_non_negative')),
    sa.CheckConstraint('quantity_confidence IS NULL OR (quantity_confidence >= 0 AND quantity_confidence <= 1)', name=op.f('ck_invoice_line_items_quantity_confidence_range')),
    sa.CheckConstraint('unit_price_confidence IS NULL OR (unit_price_confidence >= 0 AND unit_price_confidence <= 1)', name=op.f('ck_invoice_line_items_unit_price_confidence_range')),
    sa.ForeignKeyConstraint(['extraction_id'], ['invoice_extractions.extraction_id'], name=op.f('fk_invoice_line_items_extraction_id_invoice_extractions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('line_item_id', name=op.f('pk_invoice_line_items')),
    sa.UniqueConstraint('extraction_id', 'position', name='uq_invoice_line_items_extraction_id_position')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_line_items')
    op.drop_index('uq_invoice_extractions_one_active_per_document', table_name='invoice_extractions', postgresql_where=sa.text("status = 'PROCESSING'"))
    op.drop_table('invoice_extractions')
    # drop_table does not drop the native enum type; do it explicitly so a
    # re-upgrade does not fail with "type extraction_status already exists".
    sa.Enum(name='extraction_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
